### ISSUE TITLE
ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by z0z0r4** [Drelf2018/nana7mi.link#1]
![image](https://user-images.githubusercontent.com/78744121/215274312-9421867d-8acb-4228-9bcb-c20394669bd1.png)
境外无法访问，盲猜国内CDN开的境内加速，仅望周知

**Comment by Drelf2018** [comment]
可是，网页部署在github pages上啊

**Comment by Drelf2018** [comment]
你试试能打开这个网站不
[https://aliyun.nana7mi.link/live.LiveRoom(21452505).get_room_info()](https://aliyun.nana7mi.link/live.LiveRoom(21452505).get_room_info())

**Comment by z0z0r4** [comment]
可以
![image](https://user-images.githubusercontent.com/78744121/215314323-74adf9ed-ec93-4ecf-b1fe-459ed059f789.png)

**Comment by z0z0r4** [comment]
怪，我现在挂梯子又能打开了，雾
打扰了

**Comment by Drelf2018** [comment]
没事
